[2023-10-03T09:40:17.710+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-03T09:40:17.812+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-03T09:40:17.818+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:40:17.970+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_results> on 2023-10-01 00:00:00+00:00
[2023-10-03T09:40:18.008+0000] {standard_task_runner.py:57} INFO - Started process 1209 to run task
[2023-10-03T09:40:18.037+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'check_results', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp587isvst']
[2023-10-03T09:40:18.040+0000] {standard_task_runner.py:85} INFO - Job 127: Subtask check_results
[2023-10-03T09:40:18.265+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.check_results scheduled__2023-10-01T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T09:40:18.736+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='check_results' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-03T09:40:18.809+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 39, in _check_if_data_in_request
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T09:40:18.839+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=check_results, execution_date=20231001T000000, start_date=20231003T094017, end_date=20231003T094018
[2023-10-03T09:40:18.908+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 127 for task check_results (the JSON object must be str, bytes or bytearray, not NoneType; 1209)
[2023-10-03T09:40:19.023+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:40:19.150+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:38:06.668+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-03T12:38:06.742+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-03T12:38:06.745+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:38:06.934+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_results> on 2023-10-01 00:00:00+00:00
[2023-10-03T12:38:06.959+0000] {standard_task_runner.py:57} INFO - Started process 136 to run task
[2023-10-03T12:38:06.972+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'check_results', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpmdtzvhje']
[2023-10-03T12:38:06.994+0000] {standard_task_runner.py:85} INFO - Job 256: Subtask check_results
[2023-10-03T12:38:07.205+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.check_results scheduled__2023-10-01T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:38:07.784+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='check_results' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-03T12:38:07.835+0000] {logging_mixin.py:149} INFO - {"count":0,"next":null,"previous":null,"results":[]} <class 'str'>
[2023-10-03T12:38:07.836+0000] {taskinstance.py:1454} INFO - No launches for today 2023-10-01.
[2023-10-03T12:38:07.877+0000] {taskinstance.py:1373} INFO - Marking task as SKIPPED. dag_id=capstone_project, task_id=check_results, execution_date=20231001T000000, start_date=20231003T123806, end_date=20231003T123807
[2023-10-03T12:38:07.963+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-10-03T12:38:08.066+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
