[2023-10-03T09:40:17.628+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T09:40:17.656+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T09:40:17.657+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:40:17.686+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_results> on 2023-10-02 00:00:00+00:00
[2023-10-03T09:40:17.709+0000] {standard_task_runner.py:57} INFO - Started process 1206 to run task
[2023-10-03T09:40:17.768+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'check_results', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpx66dl1ot']
[2023-10-03T09:40:17.775+0000] {standard_task_runner.py:85} INFO - Job 129: Subtask check_results
[2023-10-03T09:40:18.083+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.check_results scheduled__2023-10-02T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T09:40:18.662+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='check_results' AIRFLOW_CTX_EXECUTION_DATE='2023-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-02T00:00:00+00:00'
[2023-10-03T09:40:18.744+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 39, in _check_if_data_in_request
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T09:40:18.784+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=check_results, execution_date=20231002T000000, start_date=20231003T094017, end_date=20231003T094018
[2023-10-03T09:40:18.872+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 129 for task check_results (the JSON object must be str, bytes or bytearray, not NoneType; 1206)
[2023-10-03T09:40:18.925+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:40:19.062+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:38:05.912+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T12:38:05.962+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03T12:38:05.963+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:38:06.086+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_results> on 2023-10-02 00:00:00+00:00
[2023-10-03T12:38:06.106+0000] {standard_task_runner.py:57} INFO - Started process 132 to run task
[2023-10-03T12:38:06.145+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'check_results', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp_80brqra']
[2023-10-03T12:38:06.211+0000] {standard_task_runner.py:85} INFO - Job 254: Subtask check_results
[2023-10-03T12:38:06.573+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.check_results scheduled__2023-10-02T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:38:07.120+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='check_results' AIRFLOW_CTX_EXECUTION_DATE='2023-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-02T00:00:00+00:00'
[2023-10-03T12:38:07.167+0000] {logging_mixin.py:149} INFO - {"count":0,"next":null,"previous":null,"results":[]} <class 'str'>
[2023-10-03T12:38:07.168+0000] {taskinstance.py:1454} INFO - No launches for today 2023-10-02.
[2023-10-03T12:38:07.235+0000] {taskinstance.py:1373} INFO - Marking task as SKIPPED. dag_id=capstone_project, task_id=check_results, execution_date=20231002T000000, start_date=20231003T123805, end_date=20231003T123807
[2023-10-03T12:38:07.378+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-10-03T12:38:07.591+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
